[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 100, lines = 30 }
padding = { x = 8, y = 6 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.92
blur = true
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 13.0

[shell]
program = "/usr/bin/zsh"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"
